(function(){
'use strict';
var form=document.getElementById('selector-form'),results=document.getElementById('results'),hardware=document.getElementById('hardware'),grid=document.getElementById('product-grid');
var groups=['board','size','resolution','interface','touchType','touchInterface','project','lvgl','psram'],last=null;
var products=[
{name:'ILI9341 2.8" SPI TFT + XPT2046 Touch',href:'https://embeddednerd.com/products/ili9341-xpt2046-2-8-touchscreen/',reason:'Compact SPI touchscreen for smaller ESP32 projects.',esp32:['ESP32','ESP32-S2','ESP32-S3'],sizes:['2.4–2.8"'],resolutions:['240x320','320x240'],interfaces:['SPI'],touch:['Resistive'],touchInterfaces:['SPI'],psram:false},
{name:'Waveshare ESP32-S3-Touch-LCD-4.3',href:'https://embeddednerd.com/products/waveshare-esp32-s3-touch-lcd-4-3/',reason:'Integrated ESP32-S3 touchscreen platform for 4.3-inch 800×480 graphical interfaces.',esp32:['ESP32-S3'],sizes:['4.3"'],resolutions:['800x480'],interfaces:['RGB'],touch:['Capacitive'],touchInterfaces:['I²C'],psram:true},
{name:'Waveshare ESP32-S3-Touch-LCD-7',href:'https://embeddednerd.com/products/waveshare-esp32-s3-touch-lcd-7/',reason:'Large ESP32-S3 touchscreen platform aimed at dashboards, HMI and Raspberry Pi-style interfaces.',esp32:['ESP32-S3'],sizes:['7"'],resolutions:['1024x600'],interfaces:['RGB'],touch:['Capacitive'],touchInterfaces:['I²C'],psram:true}
];
function val(n){var e=form.querySelector('input[name="'+n+'"]:checked');return e?e.value:null}
function progress(){var n=groups.filter(val).length,p=Math.round(n/9*100);document.getElementById('selection-count').textContent=n;document.getElementById('selection-percent').textContent=p+'%';document.getElementById('selection-progress').style.width=p+'%'}
function high(r){return r==='800x480'||r==='1024x600'}
function large(s){return s==='5"'||s==='7"'}
function escape(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function clearErrors(){groups.forEach(function(g){var f=form.querySelector('fieldset[data-group="'+g+'"]');if(f)f.classList.remove('has-error')})}
function validate(){clearErrors();var a={},bad=null;groups.forEach(function(g){a[g]=val(g);if(!a[g]){var f=form.querySelector('fieldset[data-group="'+g+'"]');if(f)f.classList.add('has-error');if(!bad)bad=f}});if(bad){bad.scrollIntoView({behavior:'smooth',block:'center'});var i=bad.querySelector('input');if(i)i.focus();return null}return a}
function recommend(a){
var warnings=[],reasons=[],score=100,demand=0;
if(high(a.resolution))demand+=3;if(a.interface==='RGB')demand+=3;if(a.interface==='8080 / Parallel')demand+=2;if(large(a.size))demand++;if(a.lvgl==='Yes')demand+=2;if(a.psram==='Required')demand+=2;
var board=(a.interface==='RGB'||high(a.resolution)||(a.lvgl==='Yes'&&large(a.size))||a.psram==='Required')?'ESP32-S3':(['ESP32','ESP32-S2','ESP32-S3','ESP32-C3'].indexOf(a.board)>=0?a.board:'ESP32 or ESP32-S3');
var bs=a.board==='Not sure'?'recommended':(board===a.board?'recommended':'verify');
if(bs==='verify'){score-=20;warnings.push('Your selected '+a.board+' is not the preferred board for this configuration. The tool recommends '+board+', but the exact board and display combination must still be verified.')}
if(a.board==='ESP32-C3'&&(a.interface==='RGB'||high(a.resolution))){score-=15;warnings.push('The ESP32-C3 is not the preferred platform for this high-demand display configuration. Consider an ESP32-S3 and verify the exact hardware requirements.')}
var iface=a.interface,ifs='recommended';
if(iface==='Not sure'){iface=high(a.resolution)?'RGB or 8080 / Parallel':'SPI';ifs='likely'}
if(iface==='SPI')reasons.push('SPI keeps GPIO usage relatively low and is practical for many small and medium displays.');
if(iface==='RGB'){reasons.push('RGB provides high pixel-data throughput, but requires more GPIOs and careful display timing configuration.');warnings.push('RGB displays use substantially more GPIOs than SPI. Check the exact display pinout and available ESP32 GPIOs.');if(high(a.resolution))warnings.push('High-resolution RGB displays can require significant memory for frame buffers. An ESP32-S3 with suitable PSRAM is the safer choice.')}
if(iface==='8080 / Parallel')reasons.push('8080/parallel can provide higher throughput than SPI, but uses more GPIOs and requires controller-specific verification.');
if(iface==='SPI'&&high(a.resolution)){score-=10;warnings.push('SPI can be used with some higher-resolution displays, but practical refresh performance may be lower than RGB or parallel interfaces.')}
var touch=a.touchType,ti=a.touchInterface,ts='recommended';
if(touch==='No touch')ti='N/A';
else if(touch==='Capacitive'){if(ti==='I²C'){}else if(ti==='SPI'){ts='verify';score-=5;warnings.push('SPI capacitive touch is possible, but I²C is more common. Verify the exact touch controller.')}else{ti='I²C';ts='likely';warnings.push('Many capacitive touch controllers use I²C. Verify the exact controller, address and interrupt requirements.')}}
else if(touch==='Resistive'){if(ti==='I²C'){ts='verify';score-=5;warnings.push('I²C resistive touch exists, but SPI is more commonly found with controllers such as the XPT2046. Verify the controller.')}else if(ti==='Other / Not sure'){ti='SPI';ts='likely';warnings.push('Many resistive touch controllers use SPI. Verify the exact controller and required chip-select/interrupt pins.')}}
else{touch='Capacitive or resistive — verify';ti=ti==='I²C'?'I²C':ti==='SPI'?'SPI':'I²C or SPI — verify';ts='likely';warnings.push('Touch technology is unknown. Check the touchscreen controller before assuming capacitive or resistive operation.')}
var psram=a.psram==='Required'?'Required by project':(high(a.resolution)||iface==='RGB'||(a.lvgl==='Yes'&&demand>=4)||large(a.size)?'Strongly recommended; may be required':'Not normally required');
if(psram!=='Not normally required')reasons.push('PSRAM is strongly recommended because this configuration can require larger graphics buffers or more memory.');
var lvgl=a.lvgl==='Yes'?(board==='ESP32-S3'&&(high(a.resolution)||iface==='RGB')?'Excellent fit':iface==='SPI'?'Good fit; keep buffers appropriate to available RAM':'Suitable with memory and driver verification'):a.lvgl==='No'?'Not required':'Optional; depends on UI complexity';
if(a.lvgl==='Yes')reasons.push('LVGL is suitable for graphical touchscreen interfaces, but available RAM, frame buffers and display-driver support should be checked for the exact hardware.');
if(a.size==='Other / Not sure')warnings.push('Display size is unknown. Choose according to viewing distance, enclosure space and intended UI.');
if(a.resolution==='Not sure')warnings.push('Display resolution is unknown. Verify it before choosing the final ESP32 memory and interface configuration.');
if(['IoT dashboard','Home automation','HMI / control panel','Raspberry Pi-style interface'].indexOf(a.project)>=0)reasons.push('Your project type benefits from a graphical interface, making suitable display bandwidth, touch input and GUI support important.');
var dp=(iface==='RGB'?2:0)+(iface==='8080 / Parallel'?2:0)+(high(a.resolution)?2:0)+(large(a.size)?1:0)+(a.lvgl==='Yes'?1:0)+(a.psram==='Required'?1:0)+(a.touchType!=='No touch'?1:0)+(bs==='verify'?2:0)+(ts==='verify'?1:0),difficulty=dp<=2?'Beginner':dp<=5?'Intermediate':'Advanced';
warnings.push('Not every ESP32 board is compatible with every display module. Verify the exact display controller, touch controller, pinout, voltage, memory, interface and driver support before ordering.');
reasons.unshift('The recommendation is based primarily on resolution, display interface, memory demand and your project requirements.');reasons.push('The recommended board is '+board+' because it provides the most appropriate balance of peripheral support and memory headroom for this configuration.');
return {score:Math.max(0,Math.min(100,score)),board:board,boardStatus:bs,size:a.size==='Other / Not sure'?'Choose according to enclosure and viewing distance':a.size,resolution:a.resolution==='Not sure'?'Choose according to UI requirements':a.resolution,iface:iface,ifaceStatus:ifs,touchType:touch,touchInterface:ti,touchStatus:ts,psram:psram,lvgl:lvgl,difficulty:difficulty,why:reasons.join(' '),warnings:warnings}
}
function badge(s){return '<span class="badge">'+(s==='recommended'?'Recommended':s==='likely'?'Likely compatible':'Requires verification')+'</span>'}
function render(r,a){document.getElementById('selection-text').textContent=[a.board,a.size,a.resolution,a.interface,a.touchType,a.touchInterface].join(' · ');var t=document.getElementById('confidence-title'),d=document.getElementById('confidence-detail');if(r.score>=90&&r.boardStatus!=='verify'){t.textContent='Strong configuration match';d.textContent='The selected requirements align well with the recommended hardware approach.'}else if(r.score>=75&&r.boardStatus!=='verify'){t.textContent='Good configuration match';d.textContent='The configuration is practical, but exact module specifications should still be checked.'}else{t.textContent='Requires verification';d.textContent='One or more hardware constraints need closer verification.'}
var rows=[['Recommended ESP32',r.board,r.boardStatus],['Recommended display size',r.size,'likely'],['Recommended resolution',r.resolution,'likely'],['Recommended display interface',r.iface,r.ifaceStatus],['Recommended touch technology',r.touchType,r.touchStatus],['Recommended touch interface',r.touchInterface,r.touchStatus],['PSRAM',r.psram,r.psram.indexOf('Required')!==-1?'recommended':'likely'],['LVGL suitability',r.lvgl,'likely'],['Estimated project difficulty',r.difficulty,'likely']];var tb=document.getElementById('spec-table-body');tb.innerHTML='';rows.forEach(function(x){var tr=document.createElement('tr');tr.innerHTML='<th scope="row">'+escape(x[0])+'</th><td><span class="spec-value">'+escape(x[1])+'</span>'+badge(x[2])+'</td>';tb.appendChild(tr)});document.getElementById('why-text').textContent=r.why;var wl=document.getElementById('warning-list-items');wl.innerHTML='';r.warnings.forEach(function(w){var li=document.createElement('li');li.textContent=w;wl.appendChild(li)});results.classList.remove('is-hidden')}
function match(p,r){var s=0;if(p.esp32.indexOf(r.board)>=0)s+=5;if(p.sizes.indexOf(r.size)>=0)s+=4;if(p.resolutions.indexOf(r.resolution)>=0)s+=5;if(p.interfaces.indexOf(r.iface)>=0)s+=5;if(p.touch.indexOf(r.touchType)>=0)s+=3;if(p.touchInterfaces.indexOf(r.touchInterface)>=0)s+=3;if(r.psram.indexOf('Required')>=0&&p.psram)s+=3;return s}
function renderProducts(r){grid.innerHTML='';products.map(function(p){return {p:p,s:match(p,r)}}).filter(function(x){return x.s>=5}).sort(function(a,b){return b.s-a.s}).slice(0,3).forEach(function(x){var c=document.createElement('article');c.className='product-card';c.innerHTML='<h3>'+escape(x.p.name)+'</h3><div class="product-match"><strong>'+Math.min(99,Math.round(x.s/23*100))+'% match</strong> <span>based on mapped specifications</span></div><p>'+escape(x.p.reason)+'</p><a class="btn-primary" href="'+x.p.href+'">View product</a>';grid.appendChild(c)});if(!grid.children.length)grid.innerHTML='<p>No mapped hardware currently matches this configuration. See the <a href="https://embeddednerd.com/esp32-touchscreen-displays-guide/">ESP32 Touchscreen Displays guide</a>.</p>';hardware.classList.remove('is-hidden')}
form.addEventListener('change',progress);form.addEventListener('submit',function(e){e.preventDefault();var a=validate();if(!a)return;last=recommend(a);render(last,a);renderProducts(last);results.scrollIntoView({behavior:'smooth',block:'start'})});document.getElementById('reset-btn').addEventListener('click',function(){form.reset();clearErrors();results.classList.add('is-hidden');hardware.classList.add('is-hidden');last=null;document.getElementById('copy-feedback').textContent='';progress()});document.getElementById('copy-btn').addEventListener('click',function(){if(!last)return;var t='Embedded Nerd — ESP32 Touchscreen Selector\n\nRecommended configuration:\nESP32: '+last.board+'\nDisplay size: '+last.size+'\nResolution: '+last.resolution+'\nDisplay interface: '+last.iface+'\nTouch: '+last.touchType+'\nTouch interface: '+last.touchInterface+'\nPSRAM: '+last.psram+'\nLVGL: '+last.lvgl+'\nDifficulty: '+last.difficulty+'\n\nWhy: '+last.why+'\n\nWarnings:\n'+last.warnings.map(function(w){return '- '+w}).join('\n');navigator.clipboard&&navigator.clipboard.writeText?navigator.clipboard.writeText(t).then(function(){document.getElementById('copy-feedback').textContent='Copied to clipboard.'}):document.getElementById('copy-feedback').textContent='Could not copy — select and copy manually.'});if(navigator.share){var b=document.getElementById('share-btn');b.hidden=false;b.addEventListener('click',function(){if(last)navigator.share({title:'ESP32 Touchscreen Recommendation',text:'Embedded Nerd — ESP32 Touchscreen Selector\n\nRecommended ESP32: '+last.board+'\nDisplay: '+last.size+' · '+last.resolution+'\nInterface: '+last.iface+'\nTouch: '+last.touchType+' · '+last.touchInterface+'\nPSRAM: '+last.psram}).catch(function(){})})}progress();
})();
